FROM elixir:1.19.1-otp-28
WORKDIR /app

RUN apt-get update && \
    apt-get install -y postgresql-client && \
    apt-get install -y inotify-tools && \
    mix local.hex --force && \
    mix archive.install hex phx_new --force && \
    mix local.rebar --force
